{
 "title": "Red Hat AMQ broker [ On-prem ]",
 "description": "Dashboard for monitoring Red Hat AMQ Broker or Apache artemis\r\n\r\nGit repo: https://github.com/pramodmax/artemis-grafana-dashboard",
 "tags": [
  "amq",
  "broker",
  "redhat",
  "red hat",
  "artemis",
  "apache artemis",
  "on-prem"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Instance status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up) by (instance)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(artemis_consumer_count) by (broker)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(artemis_consumer_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(artemis_connection_count) by (broker)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(artemis_connection_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Heap used per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JMV Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads) by (broker)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(jvm_threads_peak_threads) by (broker)",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Message count per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(artemis_message_count) by (broker)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durable message count per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(artemis_durable_message_count) by (broker)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(artemis_address_size) by (broker)",
     "legendFormat": "{{ address }}"
    }
   ]
  }
 ]
}