{
 "title": "Red Hat AMQ broker",
 "description": "Dashboard for monitoring Red Hat AMQ Broker or Apache artemis",
 "tags": [
  "amq",
  "broker",
  "redhat",
  "red hat",
  "artemis",
  "apache artemis"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(artemis_consumer_count{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(artemis_consumer_count{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(artemis_connection_count{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(artemis_connection_count{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "description": "Deployments = Replica missmatch  \nStatefulsets = Replica missmatch  \nDaemonsets = Replica missmatch  ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\", namespace=~\"$namespace\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_replicaset_spec_replicas{namespace=~\"$namespace\"}) - sum(kube_replicaset_status_ready_replicas{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(changes(kube_pod_status_ready{namespace=~\"$namespace\", condition=\"true\"}[5m]))",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(kube_statefulset_replicas{namespace=~\"$namespace\"}) - sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_status_number_misscheduled{namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(kube_deployment_spec_replicas{namespace=~\"$namespace\"})",
     "legendFormat": "deployments"
    },
    {
     "expr": "count(kube_statefulset_replicas{namespace=~\"$namespace\"})",
     "legendFormat": "statefulsets"
    },
    {
     "expr": "count(kube_daemonset_metadata_generation{namespace=~\"$namespace\"})",
     "legendFormat": "daemonsets"
    },
    {
     "expr": "count(kube_cronjob_info{namespace=~\"$namespace\"})",
     "legendFormat": "cronjobs"
    }
   ]
  },
  {
   "title": "JVM Heap used per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JMV Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(container_threads_max{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Message count per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(artemis_message_count{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(artemis_address_size{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ address }}"
    }
   ]
  }
 ]
}